name: Deploy to Vulcan

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Vulcan
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Setup SSH
        run: |
          umask 077
          cat << EOF > ~/id_ed25519
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOF


      - name: Deploy with SSH
        run: |
          ssh -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PubkeyAuthentication=yes -o IdentityFile=~/hackerring-deploy caf5@vulcan.moe -P 4225
